# Generated by Django 4.2.7 on 2024-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id_buku', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('penerbit', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('ukuran', models.CharField(max_length=50)),
                ('halaman', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanPendidikan',
            fields=[
                ('id_peralatan_pendidikan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_peralatan', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('kategori', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField()),
            ],
        ),
    ]
